name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./* ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/store-microservices/

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/store-microservices/
          docker-compose down
          docker-compose pull
          docker-compose up -d
          EOF
